---
name: ts-go-ls
description: TypeScript Go Language Server (Native Preview)
homepage: https://github.com/microsoft/typescript-go
licenses:
  - Apache-2.0
languages:
  - TypeScript
  - JavaScript
categories:
  - LSP
source:
  id: pkg:npm/@typescript/native-preview@latest
bin:
  tsgo: npm:tsgo
neovim:
  lspconfig: ts_go_ls
